# Generated by Django 5.2 on 2025-04-09 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', models.FloatField()),
                ('intensity', models.FloatField()),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.spectrum')),
            ],
        ),
    ]
