# Generated by Django 5.2 on 2025-08-09 03:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_prediction_spectrum'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='altitude_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='spectrum',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='core_spectr_locatio_a91465_gist'),
        ),
    ]
