# Generated by Django 5.2 on 2025-08-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_spectrum_accuracy_m_spectrum_altitude_m_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spectrum',
            name='core_spectr_locatio_a91465_gist',
        ),
        migrations.RemoveField(
            model_name='spectrum',
            name='location',
        ),
        migrations.AddField(
            model_name='spectrum',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
