# Generated by Django 5.2 on 2025-10-26 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fieldheatmappoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_soc', models.FloatField(blank=True, null=True)),
                ('max_depth_mm', models.FloatField(blank=True, null=True)),
                ('max_weight_kg', models.FloatField(blank=True, null=True)),
                ('compaction_pa', models.FloatField(blank=True, null=True)),
                ('spectrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.spectrum')),
            ],
        ),
    ]
