# Generated by Django 5.2 on 2025-10-26 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCompactionHeatmapPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compaction_heatmap_points', to='core.field')),
            ],
            options={
                'indexes': [models.Index(fields=['field', 'timestamp'], name='core_fieldc_field_i_e0bac3_idx')],
            },
        ),
    ]
