# Generated by Django 5.2 on 2025-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fieldcompactionheatmappoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
